
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Angelina Anggara ## put your name
title: 'Software Developer'  ## your title
location: Taiwan


## Social Profiles
facebook: https://www.facebook.com/angelina.anggara.1  ## your facebook account url
instagram:  https://www.instagram.com/angelinaanggara/
linkedin: https://www.linkedin.com/in/angelina-anggara-7a7b069a/



# Update all the sections by editing the files inside _includes folder.
